import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Blogr-landing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Olá Mundo</h1>
    </>
  );
}
