import Head from "next/head";
import { DesignedFuture } from "../components/DesignedFuture";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Blogr-landing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DesignedFuture />
    </>
  );
}
