import Head from "next/head";
import { DesignedFuture } from "../components/DesignedFuture";
import { Footer } from "../components/Footer";
import { Infrastructure } from "../components/Infrastructure";
import { PowerFull } from "../components/PowerFull";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Blogr-landing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DesignedFuture />
      <Infrastructure />
      <PowerFull />
      <Footer />
    </>
  );
}
